---
language: node_js
node_js:
  - "6.9"
before_install:
  - pip install --user truffleHog
  - |
    pushd /tmp
    git clone --depth 1 https://github.com/awslabs/git-secrets
    cd git-secrets
    sudo make install
    popd
env:
  - SETTINGS_PATH="$(pwd)/config/settings.yml"
script:
  - |
     SECRETS=$(git diff "$TRAVIS_COMMIT_RANGE" | git secrets --scan -)
     [[ -n "$SECRETS" ]] && echo "Failure: found secrets in repo $SECRETS" && exit 1;
     depth=$(($(git rev-list --count "$TRAVIS_COMMIT_RANGE")+1))
     echo "Running truffle hog with depth: $depth"
     high_entropy=$(trufflehog --json --entropy true  --max_depth $depth . | jq -r '.commitHash')
     [[ -n "$high_entropy" ]] && echo "FAILED: High entropy commits: $high_entropy" && exit 1
     IFS='' CHANGED_FILES=$(npm run -s jsformat -- | grep -v "unchanged")
     [[ -z $CHANGED_FILES ]] && NUM_CHANGED_FILES=0 || NUM_CHANGED_FILES=$(echo $CHANGED_FILES | wc -l)
     echo "Code formatting to be fixed in $NUM_CHANGED_FILES file(s)..."
     if [[ $NUM_CHANGED_FILES -gt 0 ]]; then
       echo "Listing modifications required.."
       git diff
       echo "FAILED: Run js-beautify(npm run jsformat)" && exit 1;
     else
       echo "No changes to the code formatting required.. "
     fi
  - "npm run -s jshint-ci"
  - "npm run -s test-ci"
  - "npm run -s jsdoc"
branches:
 only:
 - travis-setup
